#!/bin/bash

# NOTE - you have to have enabled network connections in XQuartz!
xhost + 127.0.0.1

workdir=/usr/app

docker run \
       --ipc host \
       --interactive --tty --rm \
       --workdir $workdir \
       --volume "$PWD":$workdir \
       -e DISPLAY=host.docker.internal:0 \
       -p 8888:8888 \
       sritchie/mit-scheme
